FROM postgres:11-alpine

WORKDIR /code

# Custom initialization scripts
COPY ./local_deploy/create_db.sh /docker-entrypoint-initdb.d/

COPY ./files/*   /usr/share/postgresql/13/tsearch_data/
COPY ./database/bcksis_analytics1.sql  /code/bcksis_analytics1.sql

