version: '3.7'
services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile_dev2
    container_name: db
    restart: always
    volumes:
      - ../data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

